"""Generate ``docs/REGRESSION_COVERAGE.md`` from the data it reports on.

It reads three sources:

- ``flowfreq.regression.jurisdictions``: all 56 jurisdictions and their waves
- ``flowfreq/data/regression/*.json``: equation library status per state
- ``flowfreq/data/regional_skew.csv``: regional skew status per state

The report is generated, never typed, so it cannot drift from the data.
Rerun it and commit the result whenever any of those change.
``tests/test_catalog.py::test_regression_coverage_doc_is_current`` fails if the committed report is
stale.

Usage::

    python tools/gen_regression_coverage.py
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from flowfreq.regional_skew import load_table  # noqa: E402
from flowfreq.regression.jurisdictions import JURISDICTIONS, WAVE_NAMES  # noqa: E402
from flowfreq.regression.library import DATA_DIR, load_state  # noqa: E402

OUT = REPO_ROOT / "docs" / "REGRESSION_COVERAGE.md"


def render() -> str:
    skew = load_table()
    lines = [
        "# Regression coverage",
        "",
        "Generated by `tools/gen_regression_coverage.py`. Do not edit by hand.",
        "Plan and definitions of done: `docs/MASTER_ROADMAP.md` §3.2.",
        "",
    ]
    for wave_id, wave_name in WAVE_NAMES.items():
        lines += [
            f"## Wave {wave_id}: {wave_name}",
            "",
            "| Code | Jurisdiction | Equations | Regions | Equation count | Regional skew | Issue |",
            "|---|---|---|---:|---:|---|---|",
        ]
        for j in (j for j in JURISDICTIONS if j.wave == wave_id):
            if (DATA_DIR / f"{j.code}.json").exists():
                lib = load_state(j.code)
                eq_status, n_reg, n_eq = lib.status, len(lib.regions), len(lib.equations)
                issue = f"#{lib.issue}" if lib.issue else ""
            else:
                eq_status, n_reg, n_eq, issue = "not started", 0, 0, ""
            rows = skew[skew["state"] == j.code]
            sk = ", ".join(sorted(set(rows["status"]))) if len(rows) else "not started"
            lines.append(
                f"| {j.code} | {j.name} | {eq_status} | {n_reg} | {n_eq} | {sk} | {issue} |"
            )
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    OUT.write_text(render(), encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
